import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { format,parseISO,parse } from 'date-fns'
import { useState, useEffect } from 'react';
export default function Calender() {




  const read = ()=>{
      // const read = JSON.parse(localStorage.getItem('attendance'))
    // console.log(format(parseISO(read[read.length -1 ].date),'yyyy/MM/dd: HH:mm:ss'))
  }

  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>カレンダー</h1>
      </main>
    </div>
  )


}
