import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { format,parseISO,parse } from 'date-fns'
import {useState, useEffect} from 'react';
import Link from 'next/link'

const isServer = () => typeof window === 'undefined';

function Date() {
    const stg = localStorage.getItem('attendance')
    if (stg) {
        const data = JSON.parse(stg)

        const elm = data.map((v, index) => {
            return (
                <div key="index">
                    <div>日付:{format(parseISO(v.date), 'yyyy/MM/dd')}</div>
                    <div>開始:{format(parseISO(v.start), 'yyyy/MM/dd: HH:mm:ss')}</div>
                    <div>休憩開始:{format(parseISO(v.endRest), 'yyyy/MM/dd: HH:mm:ss')}</div>
                    <div>休憩終了:{format(parseISO(v.endRest), 'yyyy/MM/dd: HH:mm:ss')}</div>
                    <div>終了:{format(parseISO(v.end), 'yyyy/MM/dd: HH:mm:ss')}</div>
                </div>
            )
        })

        return elm
    } else {
        return <div>記録がありません。</div>
    }


}

export default function Calender() {






  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>カレンダー</h1>
        <div>
            <div>
                <Link href="/">
                    <a>HOME</a>
                </Link>
            </div>
            <div>
                <Link href="/calender">
                    <a>Calender</a>
                </Link>
            </div>
        </div>
        <div>
            {!isServer() && <Date />}
        </div>
      </main>
    </div>
  )


}
