import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { format } from 'date-fns'

export default function Home() {

  const clock = () => {
    return format(new Date(),'yyyy/MM/dd:HH:mm:ss').toString()
  }

  const start = () => {
    console.log('start')
  }

  const end = () => {
    console.log('end')
  }

  const rest = () => {
    console.log('rest')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.top}>{clock()}</div>
        <div className={styles.controller}>
          <button onClick={start}>開始</button>
          <button onClick={end}>終了</button>
          <button onClick={rest}>休憩</button>
        </div>
        <div className={styles.display}>
          <div>
            <span>10:00</span>~<span>19:00</span>
          </div>
          <div>
            <span>13:00</span>~<span>14:00</span>
          </div>
        </div>
      </main>
    </div>
  )


}
